### ISSUE TITLE
It's seems that this will not work on openssh 7.5

### ISSUE THREAD

**Issue by X-HAT** [Te-k/openssh-backdoor#1]
Hello

It's seems that this will not work on openssh 7.5 because some files are deleted or updated like : sshconnect1.c

Thanks.

**Comment by Te-k** [comment]
Interesting but I am not surprised as it was used some time ago now.
I found this backdoor through honeypot, and it is here mainly to document the attack (see https://www.randhome.io/blog/2016/08/01/openssh-backdoor-used-on-compromised-linux-servers/), so I have no plan of updating it for new version. (So I am closing this issue)
